//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.05 at 01:50:07 AM WIB 
//


package com.oracle;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Authenticationheader_QNAME = new QName("http://www.oracle.com", "authenticationheader");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticationHeaderType }
     * 
     */
    public AuthenticationHeaderType createAuthenticationHeaderType() {
        return new AuthenticationHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationHeaderType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthenticationHeaderType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.oracle.com", name = "authenticationheader")
    public JAXBElement<AuthenticationHeaderType> createAuthenticationheader(AuthenticationHeaderType value) {
        return new JAXBElement<AuthenticationHeaderType>(_Authenticationheader_QNAME, AuthenticationHeaderType.class, null, value);
    }

}
